server:
  port: 9999


spring:
  application:
    name: @artifactId@
  #profiles: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://119.23.8.73:3306/pro_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: ENC(H15dJ+G7zVCtGXpZnoC8aw==)
    password: ENC(Rl4qmW/H2ukPTr5pgYwLyQIpoGBC6tjO)

  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: cloud-auth
          uri: lb://cloud-auth
          order: 8000
          predicates:
            - Path=/auth/**
          filters:
#            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: cloud-admin-service
          uri: lb://cloud-admin-service
          order: 8001
          predicates:
            - Path=/admin/**
          filters:
#            - SwaggerHeaderFilter
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                # 需要与上边的方法名保持一致
                rate-limiter: "#{@sysRedisRateLimiter}"
                #需要与策略类的方法名保持一致。
                key-resolver: "#{@sysKeyResolver}"



  # 整合redis
  redis:
    host: 119.23.8.73
    password:
    port: 8379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0

#
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cloud.admin.beans.po
  global-config:
    # 数据库相关配置
    banner: false
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

